### ISSUE TITLE
NTP Check shows perl warnings Use of uninitialized value 

### ISSUE THREAD

**Issue by Napsty** [slauger/check_netscaler#40] opened 2018-10-03 12:03 UTC
When running the plugin with ntp check command:

```
$ ./check_netscaler.pl -H mynetscaler -s -C ntp -u nsroot -p secret 
Use of uninitialized value in split at ./check_netscaler.pl line 1122.
Use of uninitialized value in split at ./check_netscaler.pl line 1131.
NetScaler OK - ntp: Offset -0.000324 secs, jitter=5.033, stratum=3, truechimers=1 | offset=-0.000324s;; jitter=5.033;;;0; stratum=3;;;0;16 truechimers=1;;;0;
```

Bad workaround: Temporarily disable perl warnings

```
$ grep "^use warnings" check_netscaler.pl
use warnings;

$ sudo sed -i "s/use warnings/#use warnings/" check_netscaler.pl

$ ./check_netscaler.pl -H mynetscaler -s -C ntp -u nsroot -p secret 
NetScaler OK - ntp: Offset -0.000324 secs, jitter=5.139, stratum=3, truechimers=1 | offset=-0.000324s;; jitter=5.139;;;0; stratum=3;;;0;16 truechimers=1;;;0;
```

Real solution: Define variables.

**Comment by slauger** [comment] 2019-09-19 11:05
I'm somehow unable to reproduce this. Could you provide a fix for this?

**Closed** 2019-12-23 22:26 UTC
Labels: help wanted
